apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  DB_SA_PASSWORD: {{ .Values.secret.saPassword | quote }}
  DB_CONNECTION_STRING: {{ .Values.secret.connectionString | quote }}
